prometheus:
  prometheusSpec:
    serviceAccountName: ${service_account_name}
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ${storage_class_name}
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: ${prometheus_storage}
        metadata:
          annotations:
            volume.beta.kubernetes.io/storage-provisioner: efs.csi.aws.com
            volume.beta.kubernetes.io/mount-options: "basePath=/prometheus"
    additionalScrapeConfigs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
      - job_name: pushgateway
        static_configs:
          - targets: ["pushgateway.${observability_namespace}.svc.cluster.local:9091"]
      - job_name: kubernetes-nodes
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
      - job_name: kubernetes-services
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
  service:
    type: ClusterIP
    port: 9090

alertmanager:
  alertmanagerSpec:
    serviceAccountName: ${service_account_name}
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: ${storage_class_name}
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: ${alertmanager_storage}
        metadata:
          annotations:
            volume.beta.kubernetes.io/storage-provisioner: efs.csi.aws.com
            volume.beta.kubernetes.io/mount-options: "basePath=/alertmanager"
  service:
    type: ClusterIP
    port: 9093

grafana:
  enabled: false
